version: "3"
services:
  api:
    #build: .
    image: blueblue001/fastapi:fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    # volumes:
    #   - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #   env_file:
    #       - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRETE_KEY=${SECRETE_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: