name: Build and Deploy Code

#on: [push, pull_request]
#on: push
on:
  push:
    branches: ["main"]

jobs:
  job1: action test
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3 
      - name: say hi
        run: echo "hello~~~~!!!"